### PR TITLE
Fix APN error spelling and robustify decoder

### PR DESCRIPTION
**Pull request by jessekempf**

### CODE REVIEW

**Comment by hce** [comment]
@jessekempf Think it makes sense to never throw an exception? If the json cannot be decoded, just return a fatal error instead?

**Comment by jessekempf** [comment]
JSON decoding failures fall into two categories:
1. Apple's response is correctly formed but contains a reason we don't explicitly handle, i.e., protocol evolution.
2. Apple's response is malformed.

I think it makes sense to treat these as fundamentally different scenarios.

**Comment by jessekempf** [comment]
I think that's untrue.

First, as an aside, I gave it some thought and a problem with the grab bag approach for otherwise-unknown reason codes is that updates to this library can change the semantics of reason-handling without the old code becoming invalid. For example, let's say Apple introduces a "Foobar" fatal error. Version A.B.x.y of this library returns `ApnFatalErrorOther "Foobar"`. Then version A.B+1.0.0 adds support for `ApnFatalErrorFoobar`, the old client code path is never exercised, but the old client code continues to compile.

As a general rule, APNS fatal errors have to do with token status. They don't represent abnormal states -- given a sufficiently large application installed base, some percentage of my tokens will be expired at any given time. I'm very resistant to the idea of these becoming exceptions as this starts getting in the neighborhood of using exceptions for flow control.

I think you could make an argument that APNS temporary errors actually _should_ be exceptions.

As a user of the library I care less about having to handle additional cases than I care that the code not surprise-crash my program and that it's fairly obvious how to write a correct client of the library. Exceptions only really make sense in the context of flagging transient errors that should restart an operation.

**Comment by hce** [comment]
Yeah, I agree, we shouldn't have both exceptions and temporary errors.

**Comment by hce** [comment]
@jessekempf Think we're ready for a new release on hackage? 0.1.1.1?

**Comment by jessekempf** [comment]
@hce: The changes are breaking, so it should be 0.2.0.0.

**Comment by hce** [comment]
You're right! thanks

**Pull request merged**
