### PR TITLE
Special-case APNS bad token responses

### PR DESCRIPTION
**Pull request by jessekempf**
I'm not sure if this technique is overly fragile.

I added this after spending some time trying to debug fatal errors which ultimately came down to using the wrong token encoder.

### CODE REVIEW

**Comment by jessekempf** [comment]
@hce: Hello?

**Comment by hce** [comment]
Hi @jessekempf  I'm sorry I didn't see the earlier message. I'll look at your pull request right away.

**Comment by hce** [comment]
Thank you very much for the pull request!

I think a small improvement would be to properly json decode the error message before handling it, what do you think?

**Comment by jessekempf** [comment]
@hce: No worries. And yes, that was a fairly ad-hoc approach on my part. Right now I've got two new changes I need to make to this library, than after that I can come back and do JSON decoding. My project is likely to need to be able to distinguish more kinds of 400 error than just the current two.

**Comment by hce** [comment]
Great! Any changes you make that are of general use, you're very welcome to create more pull requests! :-)

**Pull request merged**
